app/urls.py
from django.urls import path

from . import views

app_name = "app"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('student/<int:student_id>/', views.StudentView, name='student'),
    path('assignment/<int:assignment_id>', views.AssignmentView, name="assignment")
    # path('student/', views.StudentView.as_view(), name='student')
]

app/models.py
import datetime

from django.db import models
import django.utils


class Assignment(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(default="DESCRIPTION OF ASSIGNMENT!")
    teacher = models.CharField(max_length=20, default="YOUR NAME HERE!")
    subject = models.CharField(max_length=20, default="SUBJECT HERE!")
    pub_date = models.DateTimeField('date published', default=django.utils.timezone.now)
    due_date = models.DateTimeField('date due', default=django.utils.timezone.now)
    students = models.ManyToManyField('app.Student', blank=True)
    # student1 = models.BooleanField()
    # student2 = models.BooleanField()
    # student3 = models.BooleanField()
    # student4 = models.BooleanField()
    def __str__(self):
        return self.name
    def was_published_recently(self):
        now = django.utils.timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        was_published_recently.admin_order_field = 'pub_date'
        was_published_recently.boolean = True
        was_published_recently.short_description = 'Published recently?'
    def is_due(self):
        now = django.utils.timezone.now()


class Student(models.Model):
    # assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    # assignment = models.ManyToManyField(Assignment)
    name = models.CharField(max_length=20)
    def __str__(self):
        return self.name

app/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from datetime import datetime, time, timedelta, tzinfo

from .models import Assignment, Student


class IndexView(generic.ListView):
    model = Student
    template_name = "app/index.html"
    context_object_name = "student_list"
    def get_queryset(self):
        return Student.objects.filter()

def StudentView(request, student_id):
    student = get_object_or_404(Student, pk=student_id)
    print(f"Student {student} logged in")
    assignments = Assignment.objects.filter(students=student)
    assignment_list = assignments.order_by('-pub_date')[:10]
    print(f"{student}'s assignments are: {assignments}")
    context = {'assignment_list':assignments, 'student_name':student.name}
    return render(request, 'app/student_1.html', context)

def AssignmentView(request, assignment_id):
    assignment = get_object_or_404(Assignment, pk=assignment_id)
    now = datetime.now(timezone.utc)
    diff = assignment.due_date - now
    days = diff.days
    secs = diff.seconds

    hours = secs / 3600
    if hours < 1:
        hours = 0
    else:
        secs = secs - hours * 60

    minutes = secs / 60

    if minutes < 1:
        minutes = 0
    else:
        secs = secs - minutes * 60

    if hours < 1 and minutes < 1:
        if secs < 1:
            time = f"Overdue"
        else:
            time = f"Days: {days}, Hours: {hours}, Mins: {minutes}, Secs: {secs}"
    else:
        time = f"Days: {days}, Hours: {hours}, Mins: {minutes}"
    
    # if secs < 1:
    #     print(secs)
    #     time = f"Overdue"

    # secs = old_secs - (minutes + hours)
    # minutes = diff.minute
    # secs = diff.second
    context = {'assignment':assignment, 'diff':time, 'now': datetime.now()}
    return render(request, 'app/assignment.html', context)

# class AssignmentView(generic.ListView):
#     model = Assignment
#     template_name = "app/assignment.html"
#     context_object_name = "assignment"
#     def get_queryset(self):
#         return Assignment.objects.filter(name=get_object_or_404(Assignment, pk=pk))

app/templates/app/assignment.html
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 

<style>
    * {
        font-family: 'Roboto', sans-serif;
    }
    table {
    border-collapse: collapse;
    width: 100%;
    }

    td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
    }

    tr:nth-child(even) {
    background-color: #dddddd;
    }

    a {
        align: center;
    }
</style>

<title>Assignment Details: {{ assignment.name }}</title>
<h1>Assignment Details: {{ assignment.name }}</h1>

<table>
    <tr>
        <th>Teacher</th>
        <th>Subject</th>
        <th>Description</th>
        <th>Creation Date</th>
        <th>Due Date</th>
        <th>Time Left</th>
    </tr>
    <tr>
        <th>{{ assignment.teacher }}</th>
        <th>{{ assignment.subject }}</th>
        <th>{{ assignment.description }}</th>
        <th>{{ assignment.pub_date }}</th>
        <th>{{ assignment.due_date }}</th>
        <th>{{ diff }}</th>
    </tr>
</table>

<p>Last Updated Time: {{ now }}</p>
<p><a href="{% url 'app:index' %}">Homepage</p>

app/templates/app/index.html
{% load static %}

<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 

<style>
  * {
    font-family: 'Roboto', sans-serif;
  }

  .studentlist {
    font-size: x-large;
  }
</style>

<title>HWK Planner</title>

{% if student_list %}
    <h1>Please select your name from the list below:</h1>
    <ul>
    {% for student in student_list %}
		<li class="studentlist"><a href="{% url 'app:student' student.id %}">{{ student.name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No students are available.</p>
{% endif %}

app/templates/app/student_1.html
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet"> 

<style>
  * {
    font-family: 'Roboto', sans-serif;
  }
</style>

<title>{{ student_name }}</title>
<h1>Welcome, {{ student_name }}!</h1>
<h2>Your assignments are:</h2>
<ul>
{% for task in assignment_list %}
    <li><a href="{% url 'app:assignment' task.id %}">{{ task.name }} - {{ task.subject }} by {{ task.teacher }}</a></li>
{% endfor %}
</ul>

<p>Click on an assignment for more info!</p>